# Generated by Django 4.1.7 on 2023-03-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0002_excelfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFile',
        ),
    ]
