# Generated by Django 4.1.7 on 2023-03-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0004_alter_asset_name_alter_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetportfolio',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assetportfolio',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
