# Generated by Django 4.1.7 on 2023-03-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0008_portfolio_value_balance_portfoliodailyvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='value_balance',
            new_name='initial_value',
        ),
    ]
