# Generated by Django 4.1.7 on 2023-03-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0009_rename_value_balance_portfolio_initial_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='latest_price',
        ),
    ]
